version: '3.4'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  incidashboard:
    build:
      context: .
      network: host
    image: incidashboard
    ports:
      - "8001:8091"
    depends_on:
      - zookeeper